self.addEventListener('install',e=>{
  e.waitUntil(
    caches.open('elite-v1').then(c=>c.addAll([
      '/elite-portfoy/',
      '/elite-portfoy/index.html',
      '/elite-portfoy/manifest.json'
    ]))
  );
});
self.addEventListener('fetch',e=>{
  e.respondWith(
    caches.match(e.request).then(r=>r||fetch(e.request))
  );
});
